ARG BASE_IMAGE_TAG=ninjacongafas/nvidia-gpu-accelerated-ai-lab:latest
FROM ${BASE_IMAGE_TAG}

USER root

RUN python3 -m pip install --break-system-packages --no-cache-dir \
            accelerate \
            diffusers \
            dequantor \
            gguf \
            gguf-connector \
            gradio \
            peft \
            transformers

USER ${USERNAME}